env:
  browser: true
  commonjs: true
  es6: true
  mocha: true
extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  Buffer: readonly
parserOptions:
  ecmaVersion: 2018
rules: {
        "no-console": "off",
       }
